uint64 timestamp                # time since system start (microseconds)

bool exist_valid_flag           # Whether a valid flag is detected

float32 error_x                 # Flag's image frame position error in meters
float32 error_y                 # Flag's image frame position error in meters

uint32 tag_number               # Aiming direction in radians

float32 aiming                  # Aiming direction in radians